pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'horstis-mc-mods'

include ':core'

[
	'deathpoint', 'afk', 'killmagnet', 'anvilfix', 'keepmoving', 'totem', 'woodcutter',
	'deathswap', 'tag', 'sit', 'bounty', 'mobgriefing', 'harvest',
	'juggernaut', 'pets', 'giftburden', 'lifesteal', 'graves', 'manhunt', 'events', 'nemesis',
	'wrapped', 'toolguard', 'refill', 'spawnguard', 'horstihud'
].each { include ":mods:${it}" }
